import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

enum AppLanguage {
  english('en', 'English', 'English'),
  bengali('bn', 'বাংলা', 'Bengali');

  const AppLanguage(this.code, this.nativeName, this.englishName);

  final String code;
  final String nativeName;
  final String englishName;
}

class AppLanguageController {
  AppLanguageController._();

  static final ValueNotifier<AppLanguage> notifier =
      ValueNotifier<AppLanguage>(AppLanguage.english);

  static const _languageKey = 'app_language';

  static AppLanguage get current => notifier.value;

  static Future<void> load() async {
    final preferences = await SharedPreferences.getInstance();
    final code = preferences.getString(_languageKey);
    notifier.value = AppLanguage.values.firstWhere(
      (language) => language.code == code,
      orElse: () => AppLanguage.english,
    );
  }

  static Future<void> setLanguage(AppLanguage language) async {
    final preferences = await SharedPreferences.getInstance();
    await preferences.setString(_languageKey, language.code);
    notifier.value = language;
  }
}

class AppText {
  const AppText._();

  static String get languageName => AppLanguageController.current.nativeName;

  static String get fontFamily {
    return AppLanguageController.current == AppLanguage.bengali
        ? 'HindSiliguri'
        : 'Inter';
  }

  static String t(String key) {
    final table = AppLanguageController.current == AppLanguage.bengali
        ? _bn
        : _en;
    return table[key] ?? _en[key] ?? key;
  }

  static const _en = {
    'app_title': 'City Go Remit',
    'available_balance': 'Available Balance',
    'tap_to_show_balance': 'Tap to show balance',
    'tap_to_hide_balance': 'Tap to hide balance',
    'updating_balance': 'Updating balance...',
    'add_money': 'Add Money',
    'add_money_soon': 'Add money option will be available soon.',
    'you_send': 'You Send',
    'you_get': 'You Get',
    'continue': 'Continue',
    'processing': 'Processing...',
    'enter_valid_amount': 'Enter a valid amount.',
    'amount_limit_message': 'Amount must be between BDT :min and BDT :max.',
    'payment_link_unavailable': 'Payment link is not available right now.',
    'maintenance_title': 'We’ll be back shortly',
    'maintenance_body': 'City Go Remit is currently under scheduled maintenance. Please try again in a little while.',
    'try_again': 'Try Again',
    'service_unavailable': 'This service is temporarily unavailable.',
    'account_blocked_title': 'Account Blocked',
    'account_blocked_body': 'Your account is currently blocked. Please contact support for help.',
    'back_to_login': 'Back to Login',
    'chat_blocked': 'Live chat is unavailable for your account.',
    'account': 'ACCOUNT',
    'preferences': 'PREFERENCES',
    'personal_information': 'Personal Information',
    'personal_information_subtitle': 'Show, edit and update your profile',
    'security_settings': 'Security Settings',
    'security_settings_subtitle': 'Password, device and account safety',
    'cards_limits': 'Cards & Limits',
    'cards_limits_subtitle': 'Manage cards and transaction limits',
    'notifications': 'Notifications',
    'notifications_subtitle': 'Push alerts and account updates',
    'language': 'Language',
    'language_subtitle': 'Change app language',
    'appearance': 'Appearance',
    'appearance_subtitle': 'Light mode',
    'sign_out': 'Sign Out',
    'logout_title': 'Sign out from City Go Remit?',
    'logout_body':
        'You will need to sign in again to access your wallet and account settings.',
    'cancel': 'Cancel',
    'manage_profile': 'Manage your profile',
    'manage_profile_body':
        'Keep your account information accurate and updated.',
    'full_name': 'Full Name',
    'full_name_hint': 'Enter your full name',
    'email_address': 'Email Address',
    'email_hint': 'you@example.com',
    'phone_number': 'Phone Number',
    'phone_hint': 'Enter phone number',
    'address': 'Address',
    'address_hint': 'House, street, city',
    'save_changes': 'Save Changes',
    'profile_updated': 'Personal information updated.',
    'required_field': 'This field is required',
    'valid_email': 'Enter a valid email address',
    'email_not_set': 'Email not set',
    'phone_not_set': 'Phone not set',
    'address_not_set': 'Address not set',
    'account_protection_active': 'Account protection is active',
    'account_protection_body':
        'Your account uses password security and OTP recovery.',
    'change_password': 'Change Password',
    'change_password_body':
        'Use a password you can remember. No uppercase or number rule is required.',
    'current_password': 'Current Password',
    'current_password_hint': 'Enter current password',
    'new_password': 'New Password',
    'new_password_hint': 'Enter new password',
    'confirm_new_password': 'Confirm New Password',
    'confirm_new_password_hint': 'Repeat new password',
    'update_password': 'Update Password',
    'missing_email': 'Email is missing. Update your profile first.',
    'confirm_password_required': 'Please confirm your password',
    'passwords_do_not_match': 'Passwords do not match',
    'device_protection': 'Device Protection',
    'device_protection_body':
        'Keep your device locked and never share login details.',
    'otp_verification': 'OTP Verification',
    'otp_verification_body':
        'Password recovery is protected by email OTP verification.',
    'select_language': 'Select Language',
    'language_updated': 'Language updated successfully.',
    'home': 'Home',
    'services': 'Services',
    'all_services': 'ALL SERVICES',
    'history': 'History',
    'history_title': 'Transactions',
    'history_search_hint': 'Search by ID, category, number or status...',
    'history_total': 'Total',
    'history_in': 'In',
    'history_out': 'Out',
    'history_pending': 'Pending',
    'history_filter_all': 'All',
    'history_filter_in': 'In',
    'history_filter_out': 'Out',
    'history_filter_recharge': 'Recharge',
    'history_filter_bank_transfer': 'Bank Transfer',
    'history_filter_wallet_withdrawal': 'Wallet Withdraw',
    'history_filter_drive_offer': 'Drive Offer',
    'history_filter_pending': 'Pending',
    'history_today': 'Today',
    'history_yesterday': 'Yesterday',
    'history_recent': 'Recent',
    'history_empty': 'No transactions found',
    'history_empty_body': 'Try another keyword or filter.',
    'history_not_loaded': 'History not loaded',
    'history_type': 'Type',
    'history_direction': 'Direction',
    'history_date': 'Date',
    'history_note': 'Note',
    'settings': 'Settings',
    'payment_services': 'Payment Services',
    'youtube': 'YouTube',
    'telegram': 'Telegram',
    'social_link_unavailable': ':name link is not available right now.',
    'see_all': 'See All',
    'fund_transfer': 'Fund\nTransfer',
    'mobile_recharge': 'Mobile\nRecharge',
    'drive_offer': 'Drive\nOffer',
    'drive_offer_title': 'Drive Offers',
    'drive_offer_header': 'Live internet offers',
    'drive_offer_body': 'Choose an operator pack, confirm by email OTP and wait for admin processing.',
    'choose_offer': 'Choose Offer',
    'offers': 'offers',
    'number_after_offer': 'Enter number for selected offer',
    'number_matched': 'number matched',
    'select_drive_offer': 'Please select an internet offer.',
    'offer_operator_mismatch': 'Selected offer does not match this mobile number operator.',
    'enter_number_for_offers': 'Enter an 11-digit mobile number to filter offers by operator.',
    'no_drive_offers': 'No active offers found for this operator right now.',
    'confirm_drive_offer': 'Confirm Offer',
    'drive_offer_note': 'After OTP verification, the amount will be held from your balance. If admin rejects it, the amount will be refunded.',
    'drive_offer_submitted': 'Internet Offer Request Submitted',
    'bill_payment': 'Bill\nPayment',
    'bill_payment_title': 'Bill Payment',
    'bill_payment_header': 'Pay utility, internet, credit card, education, insurance and government bills from one secure place.',
    'bill_provider': 'Bill Provider',
    'bill_type': 'Bill Type',
    'contact_number': 'Contact Number',
    'billing_period': 'Billing Period',
    'confirm_bill_payment': 'Confirm Bill Payment',
    'service_charge': 'Service charge',
    'total': 'Total',
    'max_bill_payment': 'Maximum bill amount is BDT 500,000',
    'bill_payment_note': 'After OTP verification, your bill payment request will wait for admin approval.',
    'bill_request_submitted': 'Bill Payment Request Submitted',
    'bank_transfer': 'Bank\nTransfer',
    'bank_transfer_title': 'Bank Transfer',
    'bank_transfer_header': 'Withdraw your available balance to any Bangladesh bank account with a smooth review process.',
    'wallet_withdrawal': 'Wallet\nWithdraw',
    'wallet_withdrawal_title': 'Wallet Withdrawal',
    'wallet_withdrawal_header': 'Withdraw your available balance to bKash, Nagad or Rocket with a smooth review process.',
    'wallet_number': 'Wallet Number',
    'confirm_wallet_withdrawal': 'Confirm Wallet Withdrawal',
    'wallet_withdrawal_submitted': 'Wallet Withdrawal Request Submitted',
    'min_wallet_withdrawal': 'Minimum wallet withdrawal amount is BDT 50',
    'select_bank': 'Select Bank',
    'branch_name': 'Branch Name',
    'branch_name_hint': 'Branch name optional',
    'account_holder_name': 'Account Holder Name',
    'account_holder_hint': 'Name as per bank account',
    'bank_account_number': 'Account Number',
    'bank_account_hint': 'Enter account number',
    'routing_number': 'Routing Number',
    'routing_number_hint': 'Optional routing number',
    'withdraw_amount': 'Withdraw Amount',
    'confirm_bank_transfer': 'Confirm Bank Transfer',
    'bank_transfer_note': 'After OTP verification, your balance will be held and the transfer will wait for admin processing.',
    'bank_transfer_submitted': 'Bank Transfer Request Submitted',
    'invalid_bank_account': 'Enter a valid bank account number',
    'min_bank_transfer': 'Minimum bank transfer amount is BDT 100',
    'tap_pay': 'Tap &\nPay',
    'recharge_title': 'Mobile Recharge',
    'recharge_header_title': 'Fast mobile recharge',
    'recharge_header_body':
        'Enter an 11-digit number. Operator will be detected automatically.',
    'mobile_number': 'Mobile Number',
    'mobile_number_hint': '01XXXXXXXXX',
    'detected_operator': 'Detected Operator',
    'operator_waiting': 'Enter number to detect operator',
    'unsupported_operator': 'Unsupported operator',
    'amount': 'Amount',
    'amount_hint': 'Enter amount',
    'send_otp': 'Send OTP',
    'confirm_recharge': 'Confirm Recharge',
    'otp_code': 'OTP Code',
    'otp_hint': '6-digit OTP',
    'otp_sent_message': 'A confirmation OTP has been sent to your email.',
    'recharge_note':
        'After OTP verification, your request will wait for admin approval.',
    'missing_recharge_email': 'Please update your email before recharge.',
    'invalid_mobile_number': 'Enter a valid 11-digit mobile number',
    'invalid_operator_number': 'Could not detect a supported operator',
    'invalid_amount': 'Enter a valid amount',
    'min_recharge': 'Minimum recharge amount is ৳10',
    'max_recharge': 'Maximum recharge amount is ৳50,000',
    'invalid_otp': 'Enter a valid 6-digit OTP',
    'recharge_successful': 'Recharge Request Submitted',
    'transaction_id': 'Transaction ID',
    'operator': 'Operator',
    'done': 'Done',
    'live_chat': 'Live Chat',
    'support_chat': 'Support\nChat',
    'chat_header': 'Chat with support in real time. Typing, seen and unread status stay synced while the app is open.',
    'chat_input_hint': 'Write your message...',
    'chat_empty': 'No messages yet',
    'chat_empty_body': 'Send a message and our support team will reply here.',
    'chat_typing': 'Support is typing...',
    'chat_seen': 'Seen',
    'chat_delivered': 'Delivered',
    'chat_send': 'Send',
    'chat_loading': 'Loading chat...',
    'exchange': 'Exchange',
    'exchange_rates_title': 'Exchange Rates',
    'exchange_header_title': 'Today’s Rates',
    'exchange_header_body': 'Check the latest country rates.',
    'exchange_search_hint': 'Search country or currency',
    'exchange_empty': 'No active exchange rates found',
    'delivery_time': 'Delivery time',
    'prayer_schedule': 'Prayer Schedule',
    'detecting_location': 'Detecting location...',
    'prayer_unavailable': 'Prayer schedule is unavailable right now.',
    'retry': 'Retry',
    'prayer_fajr': 'Fajr',
    'prayer_sunrise': 'Sunrise',
    'prayer_dhuhr': 'Dhuhr',
    'prayer_asr': 'Asr',
    'prayer_maghrib': 'Maghrib',
    'prayer_isha': 'Isha',
  };

  static const _bn = {
    'app_title': 'City Go Remit',
    'available_balance': 'উপলব্ধ ব্যালেন্স',
    'tap_to_show_balance': 'ব্যালেন্স দেখতে ট্যাপ করুন',
    'tap_to_hide_balance': 'ব্যালেন্স লুকাতে ট্যাপ করুন',
    'updating_balance': 'ব্যালেন্স আপডেট হচ্ছে...',
    'add_money': 'অ্যাড মানি',
    'add_money_soon': 'অ্যাড মানি অপশন শিগগিরই চালু হবে।',
    'you_send': 'আপনি পাঠাবেন',
    'you_get': 'আপনি পাবেন',
    'continue': 'কন্টিনিউ',
    'processing': 'প্রসেস হচ্ছে...',
    'enter_valid_amount': 'সঠিক পরিমাণ লিখুন।',
    'amount_limit_message': 'পরিমাণ BDT :min থেকে BDT :max এর মধ্যে হতে হবে।',
    'payment_link_unavailable': 'পেমেন্ট লিংক এখন পাওয়া যাচ্ছে না।',
    'maintenance_title': 'আমরা শিগগিরই ফিরছি',
    'maintenance_body': 'City Go Remit এখন মেইনটেন্যান্সে আছে। অনুগ্রহ করে কিছুক্ষণ পর আবার চেষ্টা করুন।',
    'try_again': 'আবার চেষ্টা করুন',
    'service_unavailable': 'এই সার্ভিসটি সাময়িকভাবে বন্ধ আছে।',
    'account_blocked_title': 'অ্যাকাউন্ট ব্লক করা হয়েছে',
    'account_blocked_body': 'আপনার অ্যাকাউন্ট বর্তমানে ব্লক করা আছে। সাহায্যের জন্য সাপোর্টে যোগাযোগ করুন।',
    'back_to_login': 'লগইনে ফিরুন',
    'chat_blocked': 'আপনার অ্যাকাউন্টের জন্য লাইভ চ্যাট বন্ধ আছে।',
    'account': 'অ্যাকাউন্ট',
    'preferences': 'পছন্দসমূহ',
    'personal_information': 'ব্যক্তিগত তথ্য',
    'personal_information_subtitle':
        'আপনার প্রোফাইল দেখুন, এডিট করুন ও আপডেট করুন',
    'security_settings': 'সিকিউরিটি সেটিংস',
    'security_settings_subtitle': 'পাসওয়ার্ড, ডিভাইস ও অ্যাকাউন্ট নিরাপত্তা',
    'cards_limits': 'কার্ড ও লিমিট',
    'cards_limits_subtitle': 'কার্ড এবং ট্রানজ্যাকশন লিমিট ম্যানেজ করুন',
    'notifications': 'নোটিফিকেশন',
    'notifications_subtitle': 'পুশ অ্যালার্ট ও অ্যাকাউন্ট আপডেট',
    'language': 'ভাষা',
    'language_subtitle': 'অ্যাপের ভাষা পরিবর্তন করুন',
    'appearance': 'অ্যাপিয়ারেন্স',
    'appearance_subtitle': 'লাইট মোড',
    'sign_out': 'সাইন আউট',
    'logout_title': 'City Go Remit থেকে সাইন আউট করবেন?',
    'logout_body':
        'ওয়ালেট ও অ্যাকাউন্ট সেটিংস ব্যবহার করতে আবার সাইন ইন করতে হবে।',
    'cancel': 'ক্যানসেল',
    'manage_profile': 'আপনার প্রোফাইল ম্যানেজ করুন',
    'manage_profile_body': 'আপনার অ্যাকাউন্টের তথ্য সঠিক ও আপডেটেড রাখুন।',
    'full_name': 'পূর্ণ নাম',
    'full_name_hint': 'আপনার পূর্ণ নাম লিখুন',
    'email_address': 'ইমেইল ঠিকানা',
    'email_hint': 'you@example.com',
    'phone_number': 'ফোন নম্বর',
    'phone_hint': 'ফোন নম্বর লিখুন',
    'address': 'ঠিকানা',
    'address_hint': 'বাড়ি, রাস্তা, শহর',
    'save_changes': 'পরিবর্তন সেভ করুন',
    'profile_updated': 'ব্যক্তিগত তথ্য আপডেট হয়েছে।',
    'required_field': 'এই ঘরটি পূরণ করা জরুরি',
    'valid_email': 'সঠিক ইমেইল ঠিকানা লিখুন',
    'email_not_set': 'ইমেইল সেট করা নেই',
    'phone_not_set': 'ফোন সেট করা নেই',
    'address_not_set': 'ঠিকানা সেট করা নেই',
    'account_protection_active': 'অ্যাকাউন্ট সুরক্ষা চালু আছে',
    'account_protection_body':
        'আপনার অ্যাকাউন্ট পাসওয়ার্ড সিকিউরিটি ও OTP রিকভারি ব্যবহার করে।',
    'change_password': 'পাসওয়ার্ড পরিবর্তন',
    'change_password_body':
        'মনে রাখা সহজ এমন পাসওয়ার্ড দিন। বড় হাতের অক্ষর বা সংখ্যা বাধ্যতামূলক নয়।',
    'current_password': 'বর্তমান পাসওয়ার্ড',
    'current_password_hint': 'বর্তমান পাসওয়ার্ড লিখুন',
    'new_password': 'নতুন পাসওয়ার্ড',
    'new_password_hint': 'নতুন পাসওয়ার্ড লিখুন',
    'confirm_new_password': 'নতুন পাসওয়ার্ড নিশ্চিত করুন',
    'confirm_new_password_hint': 'নতুন পাসওয়ার্ড আবার লিখুন',
    'update_password': 'পাসওয়ার্ড আপডেট করুন',
    'missing_email': 'ইমেইল নেই। আগে প্রোফাইল আপডেট করুন।',
    'confirm_password_required': 'পাসওয়ার্ড নিশ্চিত করুন',
    'passwords_do_not_match': 'পাসওয়ার্ড মিলছে না',
    'device_protection': 'ডিভাইস প্রোটেকশন',
    'device_protection_body':
        'ডিভাইস লক রাখুন এবং লগইন তথ্য কখনো শেয়ার করবেন না।',
    'otp_verification': 'OTP ভেরিফিকেশন',
    'otp_verification_body':
        'পাসওয়ার্ড রিকভারি ইমেইল OTP ভেরিফিকেশন দিয়ে সুরক্ষিত।',
    'select_language': 'ভাষা নির্বাচন করুন',
    'language_updated': 'ভাষা সফলভাবে আপডেট হয়েছে।',
    'home': 'হোম',
    'services': 'সার্ভিস',
    'all_services': 'সব সার্ভিস',
    'history': 'হিস্টোরি',
    'history_title': 'ট্রানজ্যাকশন',
    'history_search_hint': 'ID, ক্যাটেগরি, নম্বর বা স্ট্যাটাস দিয়ে খুঁজুন...',
    'history_total': 'মোট',
    'history_in': 'ইন',
    'history_out': 'আউট',
    'history_pending': 'পেন্ডিং',
    'history_filter_all': 'সব',
    'history_filter_in': 'ইন',
    'history_filter_out': 'আউট',
    'history_filter_recharge': 'রিচার্জ',
    'history_filter_bank_transfer': 'ব্যাংক ট্রান্সফার',
    'history_filter_wallet_withdrawal': 'ওয়ালেট উইথড্র',
    'history_filter_drive_offer': 'ড্রাইভ অফার',
    'history_filter_pending': 'পেন্ডিং',
    'history_today': 'আজ',
    'history_yesterday': 'গতকাল',
    'history_recent': 'সাম্প্রতিক',
    'history_empty': 'কোনো ট্রানজ্যাকশন পাওয়া যায়নি',
    'history_empty_body': 'অন্য কীওয়ার্ড বা ফিল্টার দিয়ে চেষ্টা করুন।',
    'history_not_loaded': 'হিস্টোরি লোড হয়নি',
    'history_type': 'ধরন',
    'history_direction': 'দিক',
    'history_date': 'তারিখ',
    'history_note': 'নোট',
    'settings': 'সেটিংস',
    'payment_services': 'পেমেন্ট সার্ভিস',
    'youtube': 'ইউটিউব',
    'telegram': 'টেলিগ্রাম',
    'social_link_unavailable': ':name লিংক এখন পাওয়া যাচ্ছে না।',
    'see_all': 'সব দেখুন',
    'fund_transfer': 'ফান্ড\nট্রান্সফার',
    'mobile_recharge': 'মোবাইল\nরিচার্জ',
    'drive_offer': 'ড্রাইভ\nঅফার',
    'drive_offer_title': 'ড্রাইভ অফার',
    'drive_offer_header': 'লাইভ ইন্টারনেট অফার',
    'drive_offer_body': 'অপারেটর প্যাক বেছে নিন, ইমেইল OTP দিয়ে কনফার্ম করুন এবং অ্যাডমিন প্রসেসিংয়ের জন্য অপেক্ষা করুন।',
    'choose_offer': 'অফার বাছাই করুন',
    'offers': 'অফার',
    'number_after_offer': 'নির্বাচিত অফারের জন্য নম্বর দিন',
    'number_matched': 'নম্বর মিলেছে',
    'select_drive_offer': 'একটি ইন্টারনেট অফার নির্বাচন করুন।',
    'offer_operator_mismatch': 'নির্বাচিত অফার এই মোবাইল নম্বরের অপারেটরের সাথে মিলছে না।',
    'enter_number_for_offers': 'অপারেটর অনুযায়ী অফার দেখতে ১১ ডিজিটের মোবাইল নম্বর লিখুন।',
    'no_drive_offers': 'এই অপারেটরের জন্য এখন কোনো সক্রিয় অফার নেই।',
    'confirm_drive_offer': 'অফার নিশ্চিত করুন',
    'drive_offer_note': 'OTP ভেরিফাই করার পর আপনার ব্যালেন্স থেকে টাকা হোল্ড হবে। অ্যাডমিন রিজেক্ট করলে টাকা রিফান্ড হবে।',
    'drive_offer_submitted': 'ইন্টারনেট অফার রিকোয়েস্ট সাবমিট হয়েছে',
    'bill_payment': 'বিল\nপেমেন্ট',
    'bill_payment_title': 'বিল পেমেন্ট',
    'bill_payment_header': 'ইউটিলিটি, ইন্টারনেট, ক্রেডিট কার্ড, শিক্ষা, ইনস্যুরেন্স ও সরকারি বিল এক জায়গা থেকেই পেমেন্ট করুন।',
    'bill_provider': 'বিল প্রোভাইডার',
    'bill_type': 'বিল টাইপ',
    'contact_number': 'যোগাযোগ নম্বর',
    'billing_period': 'বিলিং পিরিয়ড',
    'confirm_bill_payment': 'বিল পেমেন্ট নিশ্চিত করুন',
    'service_charge': 'সার্ভিস চার্জ',
    'total': 'মোট',
    'max_bill_payment': 'সর্বোচ্চ বিল পরিমাণ BDT 500,000',
    'bill_payment_note': 'OTP ভেরিফাই করার পর আপনার বিল পেমেন্ট রিকোয়েস্ট অ্যাডমিন অনুমোদনের জন্য অপেক্ষা করবে।',
    'bill_request_submitted': 'বিল পেমেন্ট রিকোয়েস্ট সাবমিট হয়েছে',
    'bank_transfer': 'ব্যাংক\nট্রান্সফার',
    'bank_transfer_title': 'ব্যাংক ট্রান্সফার',
    'bank_transfer_header': 'সহজ রিভিউ প্রসেসের মাধ্যমে বাংলাদেশের যেকোনো ব্যাংক অ্যাকাউন্টে ব্যালেন্স উইথড্র করুন।',
    'wallet_withdrawal': 'ওয়ালেট\nউইথড্র',
    'wallet_withdrawal_title': 'ওয়ালেট উইথড্র',
    'wallet_withdrawal_header': 'সহজ রিভিউ প্রসেসের মাধ্যমে bKash, Nagad বা Rocket-এ ব্যালেন্স উইথড্র করুন।',
    'wallet_number': 'ওয়ালেট নম্বর',
    'confirm_wallet_withdrawal': 'ওয়ালেট উইথড্র নিশ্চিত করুন',
    'wallet_withdrawal_submitted': 'ওয়ালেট উইথড্র রিকোয়েস্ট সাবমিট হয়েছে',
    'min_wallet_withdrawal': 'সর্বনিম্ন ওয়ালেট উইথড্র BDT 50',
    'select_bank': 'ব্যাংক নির্বাচন করুন',
    'branch_name': 'ব্রাঞ্চের নাম',
    'branch_name_hint': 'ব্রাঞ্চের নাম ঐচ্ছিক',
    'account_holder_name': 'অ্যাকাউন্ট হোল্ডারের নাম',
    'account_holder_hint': 'ব্যাংক অ্যাকাউন্টের নাম লিখুন',
    'bank_account_number': 'অ্যাকাউন্ট নম্বর',
    'bank_account_hint': 'অ্যাকাউন্ট নম্বর লিখুন',
    'routing_number': 'রাউটিং নম্বর',
    'routing_number_hint': 'রাউটিং নম্বর ঐচ্ছিক',
    'withdraw_amount': 'উইথড্র পরিমাণ',
    'confirm_bank_transfer': 'ব্যাংক ট্রান্সফার নিশ্চিত করুন',
    'bank_transfer_note': 'OTP ভেরিফাই করার পর ব্যালেন্স হোল্ড হবে এবং ট্রান্সফার অ্যাডমিন প্রসেসিংয়ের জন্য অপেক্ষা করবে।',
    'bank_transfer_submitted': 'ব্যাংক ট্রান্সফার রিকোয়েস্ট সাবমিট হয়েছে',
    'invalid_bank_account': 'সঠিক ব্যাংক অ্যাকাউন্ট নম্বর লিখুন',
    'min_bank_transfer': 'সর্বনিম্ন ব্যাংক ট্রান্সফার BDT 100',
    'tap_pay': 'ট্যাপ ও\nপে',
    'recharge_title': 'মোবাইল রিচার্জ',
    'recharge_header_title': 'দ্রুত মোবাইল রিচার্জ',
    'recharge_header_body':
        '১১ ডিজিটের নম্বর লিখুন। অপারেটর অটোমেটিক শনাক্ত হবে।',
    'mobile_number': 'মোবাইল নম্বর',
    'mobile_number_hint': '01XXXXXXXXX',
    'detected_operator': 'শনাক্ত অপারেটর',
    'operator_waiting': 'অপারেটর শনাক্ত করতে নম্বর লিখুন',
    'unsupported_operator': 'এই অপারেটর সাপোর্টেড নয়',
    'amount': 'পরিমাণ',
    'amount_hint': 'পরিমাণ লিখুন',
    'send_otp': 'OTP পাঠান',
    'confirm_recharge': 'রিচার্জ নিশ্চিত করুন',
    'otp_code': 'OTP কোড',
    'otp_hint': '৬ ডিজিটের OTP',
    'otp_sent_message': 'আপনার ইমেইলে কনফার্মেশন OTP পাঠানো হয়েছে।',
    'recharge_note': 'OTP ভেরিফাই করার পর আপনার রিকোয়েস্ট অ্যাডমিন অনুমোদনের জন্য অপেক্ষা করবে।',
    'missing_recharge_email': 'রিচার্জের আগে আপনার ইমেইল আপডেট করুন।',
    'invalid_mobile_number': 'সঠিক ১১ ডিজিটের মোবাইল নম্বর লিখুন',
    'invalid_operator_number': 'সাপোর্টেড অপারেটর শনাক্ত করা যায়নি',
    'invalid_amount': 'সঠিক পরিমাণ লিখুন',
    'min_recharge': 'সর্বনিম্ন রিচার্জ ৳১০',
    'max_recharge': 'সর্বোচ্চ রিচার্জ ৳৫০,০০০',
    'invalid_otp': 'সঠিক ৬ ডিজিটের OTP লিখুন',
    'recharge_successful': 'রিচার্জ রিকোয়েস্ট সাবমিট হয়েছে',
    'transaction_id': 'ট্রানজ্যাকশন আইডি',
    'operator': 'অপারেটর',
    'done': 'সম্পন্ন',
    'live_chat': 'লাইভ চ্যাট',
    'support_chat': 'সাপোর্ট\nচ্যাট',
    'chat_header': 'সাপোর্টের সাথে লাইভ চ্যাট করুন। অ্যাপ খোলা থাকলে টাইপিং, seen ও unread স্ট্যাটাস সিঙ্ক থাকবে।',
    'chat_input_hint': 'আপনার মেসেজ লিখুন...',
    'chat_empty': 'এখনো কোনো মেসেজ নেই',
    'chat_empty_body': 'একটি মেসেজ পাঠান, সাপোর্ট টিম এখানেই রিপ্লাই করবে।',
    'chat_typing': 'সাপোর্ট টাইপ করছে...',
    'chat_seen': 'দেখা হয়েছে',
    'chat_delivered': 'ডেলিভার্ড',
    'chat_send': 'পাঠান',
    'chat_loading': 'চ্যাট লোড হচ্ছে...',
    'exchange': 'এক্সচেঞ্জ',
    'exchange_rates_title': 'এক্সচেঞ্জ রেট',
    'exchange_header_title': 'আজকের রেট',
    'exchange_header_body': 'সর্বশেষ দেশের রেট দেখুন।',
    'exchange_search_hint': 'দেশ বা কারেন্সি সার্চ করুন',
    'exchange_empty': 'কোনো সক্রিয় এক্সচেঞ্জ রেট পাওয়া যায়নি',
    'delivery_time': 'ডেলিভারি সময়',
    'prayer_schedule': 'নামাজের সময়সূচি',
    'detecting_location': 'লোকেশন দেখা হচ্ছে...',
    'prayer_unavailable': 'নামাজের সময়সূচি এখন পাওয়া যাচ্ছে না।',
    'retry': 'আবার চেষ্টা',
    'prayer_fajr': 'ফজর',
    'prayer_sunrise': 'সূর্যোদয়',
    'prayer_dhuhr': 'যোহর',
    'prayer_asr': 'আসর',
    'prayer_maghrib': 'মাগরিব',
    'prayer_isha': 'ইশা',
  };
}
