<?php

use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\Admin\AuthController as AdminApiAuthController;
use App\Http\Controllers\Api\Admin\BannerController as AdminApiBannerController;
use App\Http\Controllers\Api\Admin\BankTransferController as AdminApiBankTransferController;
use App\Http\Controllers\Api\Admin\BillPaymentController as AdminApiBillPaymentController;
use App\Http\Controllers\Api\Admin\ChatController as AdminApiChatController;
use App\Http\Controllers\Api\Admin\DashboardController as AdminApiDashboardController;
use App\Http\Controllers\Api\Admin\DriveOfferController as AdminApiDriveOfferController;
use App\Http\Controllers\Api\Admin\DriveOfferOrderController as AdminApiDriveOfferOrderController;
use App\Http\Controllers\Api\Admin\ExchangeRateController as AdminApiExchangeRateController;
use App\Http\Controllers\Api\Admin\GeneralSettingController as AdminApiGeneralSettingController;
use App\Http\Controllers\Api\Admin\MobileRechargeController as AdminApiMobileRechargeController;
use App\Http\Controllers\Api\Admin\NotificationController as AdminApiNotificationController;
use App\Http\Controllers\Api\Admin\ProfileController as AdminApiProfileController;
use App\Http\Controllers\Api\Admin\ReferralController as AdminApiReferralController;
use App\Http\Controllers\Api\Admin\UserController as AdminApiUserController;
use App\Http\Controllers\Api\Admin\WalletWithdrawalController as AdminApiWalletWithdrawalController;
use App\Http\Controllers\Api\AppNotificationController;
use App\Http\Controllers\Api\AppSettingController;
use App\Http\Controllers\Api\HistoryController;
use App\Http\Controllers\Api\BankTransferController;
use App\Http\Controllers\Api\BannerController;
use App\Http\Controllers\Api\BeneficiaryController;
use App\Http\Controllers\Api\BillPaymentController;
use App\Http\Controllers\Api\ChatController;
use App\Http\Controllers\Api\DriveOfferController;
use App\Http\Controllers\Api\ExchangeRateController;
use App\Http\Controllers\Api\MobileRechargeController;
use App\Http\Controllers\Api\NotificationTokenController;
use App\Http\Controllers\Api\ReceiptController;
use App\Http\Controllers\Api\RegisteredUserController;
use App\Http\Controllers\Api\SecurityController;
use App\Http\Controllers\Api\WalletWithdrawalController;
use Illuminate\Support\Facades\Route;

Route::post('/login', [AuthController::class, 'login'])->name('api.login');
Route::get('/banners', [BannerController::class, 'index'])->name('api.banners.index');
Route::get('/banners/{banner}/image', [BannerController::class, 'image'])->name('api.banners.image');
Route::get('/settings', [AppSettingController::class, 'show'])->name('api.settings.show');
Route::get('/profile', [AuthController::class, 'profile'])->name('api.profile');
Route::post('/notification-token', [NotificationTokenController::class, 'store'])->name('api.notification-token.store');
Route::delete('/notification-token', [NotificationTokenController::class, 'destroy'])->name('api.notification-token.destroy');
Route::post('/register', RegisteredUserController::class)->name('api.register');
Route::post('/kyc-register', [RegisteredUserController::class, 'kycRegister'])->name('api.kyc-register');
Route::post('/register/verify-otp', [RegisteredUserController::class, 'verifyOtp'])->name('api.register.verify-otp');
Route::post('/forgot-password', [AuthController::class, 'forgotPassword'])->name('api.forgot-password');
Route::post('/forgot-password/verify-otp', [AuthController::class, 'resetPasswordWithOtp'])->name('api.forgot-password.verify-otp');
Route::post('/change-password', [AuthController::class, 'changePassword'])->name('api.change-password');
Route::post('/mobile-recharge/request-otp', [MobileRechargeController::class, 'requestOtp'])->name('api.mobile-recharge.request-otp');
Route::post('/mobile-recharge/confirm', [MobileRechargeController::class, 'confirm'])->name('api.mobile-recharge.confirm');
Route::get('/mobile-recharges', [MobileRechargeController::class, 'index'])->name('api.mobile-recharge.index');
Route::post('/bill-payment/request-otp', [BillPaymentController::class, 'requestOtp'])->name('api.bill-payment.request-otp');
Route::post('/bill-payment/confirm', [BillPaymentController::class, 'confirm'])->name('api.bill-payment.confirm');
Route::get('/bill-payments', [BillPaymentController::class, 'index'])->name('api.bill-payment.index');
Route::post('/bank-transfer/request-otp', [BankTransferController::class, 'requestOtp'])->name('api.bank-transfer.request-otp');
Route::post('/bank-transfer/confirm', [BankTransferController::class, 'confirm'])->name('api.bank-transfer.confirm');
Route::get('/bank-transfers', [BankTransferController::class, 'index'])->name('api.bank-transfer.index');
Route::post('/wallet-withdrawal/request-otp', [WalletWithdrawalController::class, 'requestOtp'])->name('api.wallet-withdrawal.request-otp');
Route::post('/wallet-withdrawal/confirm', [WalletWithdrawalController::class, 'confirm'])->name('api.wallet-withdrawal.confirm');
Route::get('/wallet-withdrawals', [WalletWithdrawalController::class, 'index'])->name('api.wallet-withdrawal.index');
Route::get('/drive-offers', [DriveOfferController::class, 'index'])->name('api.drive-offers.index');
Route::get('/exchange-rates', [ExchangeRateController::class, 'index'])->name('api.exchange-rates.index');
Route::post('/drive-offer/request-otp', [DriveOfferController::class, 'requestOtp'])->name('api.drive-offer.request-otp');
Route::post('/drive-offer/confirm', [DriveOfferController::class, 'confirm'])->name('api.drive-offer.confirm');
Route::get('/drive-offer-orders', [DriveOfferController::class, 'orders'])->name('api.drive-offer.orders');
Route::get('/chat', [ChatController::class, 'show'])->name('api.chat.show');
Route::post('/chat/messages', [ChatController::class, 'send'])->name('api.chat.messages');
Route::post('/chat/typing', [ChatController::class, 'typing'])->name('api.chat.typing');
Route::post('/chat/seen', [ChatController::class, 'seen'])->name('api.chat.seen');
Route::get('/chat/messages/{message}/attachment', [ChatController::class, 'attachment'])->name('api.chat.attachment');
Route::get('/histories', HistoryController::class)->name('api.histories');
Route::get('/beneficiaries', [BeneficiaryController::class, 'index'])->name('api.beneficiaries.index');
Route::post('/beneficiaries', [BeneficiaryController::class, 'store'])->name('api.beneficiaries.store');
Route::put('/beneficiaries/{beneficiary}', [BeneficiaryController::class, 'update'])->name('api.beneficiaries.update');
Route::delete('/beneficiaries/{beneficiary}', [BeneficiaryController::class, 'destroy'])->name('api.beneficiaries.destroy');
Route::get('/notifications', [AppNotificationController::class, 'index'])->name('api.notifications.index');
Route::post('/notifications/read', [AppNotificationController::class, 'markRead'])->name('api.notifications.read');
Route::get('/security/devices', [SecurityController::class, 'devices'])->name('api.security.devices');
Route::get('/receipts/{type}/{transactionId}', [ReceiptController::class, 'show'])->name('api.receipts.show');

Route::prefix('admin')->name('api.admin.')->group(function (): void {
    Route::post('/login', [AdminApiAuthController::class, 'login'])->name('login');

    Route::middleware('admin.api')->group(function (): void {
        Route::get('/me', [AdminApiAuthController::class, 'me'])->name('me');
        Route::post('/logout', [AdminApiAuthController::class, 'logout'])->name('logout');
        Route::put('/profile', [AdminApiProfileController::class, 'update'])->name('profile.update');
        Route::put('/profile/password', [AdminApiProfileController::class, 'changePassword'])->name('profile.password');
        Route::get('/dashboard', AdminApiDashboardController::class)->name('dashboard');
        Route::get('/general-settings', [AdminApiGeneralSettingController::class, 'show'])->name('general-settings.show');
        Route::put('/general-settings', [AdminApiGeneralSettingController::class, 'update'])->name('general-settings.update');
        Route::get('/banners', [AdminApiBannerController::class, 'index'])->name('banners.index');
        Route::post('/banners', [AdminApiBannerController::class, 'store'])->name('banners.store');
        Route::post('/banners/{banner}', [AdminApiBannerController::class, 'update'])->name('banners.update');
        Route::delete('/banners/{banner}', [AdminApiBannerController::class, 'destroy'])->name('banners.destroy');
        Route::get('/notifications', [AdminApiNotificationController::class, 'index'])->name('notifications.index');
        Route::post('/notifications/send', [AdminApiNotificationController::class, 'send'])->name('notifications.send');
        Route::get('/referrals', [AdminApiReferralController::class, 'index'])->name('referrals.index');
        Route::put('/referrals', [AdminApiReferralController::class, 'update'])->name('referrals.update');
        Route::apiResource('users', AdminApiUserController::class);
        Route::apiResource('recharges', AdminApiMobileRechargeController::class)->only(['index', 'show', 'update']);
        Route::apiResource('bill-payments', AdminApiBillPaymentController::class)->only(['index', 'update']);
        Route::apiResource('bank-transfers', AdminApiBankTransferController::class)->only(['index', 'update']);
        Route::apiResource('wallet-withdrawals', AdminApiWalletWithdrawalController::class)->only(['index', 'update']);
        Route::apiResource('drive-offers', AdminApiDriveOfferController::class)->only(['index', 'store', 'update', 'destroy']);
        Route::apiResource('drive-offer-orders', AdminApiDriveOfferOrderController::class)->only(['index', 'update']);
        Route::apiResource('exchange-rates', AdminApiExchangeRateController::class)->only(['index', 'store', 'update', 'destroy']);
        Route::get('/chats', [AdminApiChatController::class, 'index'])->name('chats.index');
        Route::get('/chats/{conversation}', [AdminApiChatController::class, 'show'])->name('chats.show');
        Route::put('/chats/{conversation}', [AdminApiChatController::class, 'update'])->name('chats.update');
        Route::post('/chats/{conversation}/messages', [AdminApiChatController::class, 'send'])->name('chats.messages');
        Route::post('/chats/{conversation}/typing', [AdminApiChatController::class, 'typing'])->name('chats.typing');
        Route::post('/chats/{conversation}/seen', [AdminApiChatController::class, 'seen'])->name('chats.seen');
    });
});
